imports:
    - { resource: config_dev.yml }


doctrine:
    dbal:
        driver:   %test_db_driver%
        host:     %test_db_host%
        port:     %test_db_port%
        dbname:   %test_db_name%
        user:     %test_db_user%
        password: %test_db_password%
        path:     %test_db_path%
        charset:  UTF8
        ## SQLite In-Memory Config
        #driver:   pdo_sqlite
        #path:     :memory:
        #memory:   true

        ## SQLite File Config
        #driver:   pdo_sqlite
        #path:     "%kernel.root_dir%/cache/test/data.sqlite"

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
